### ISSUE TITLE
Add Ambassadors' LinkedIn links to the Landing Page

### ISSUE THREAD

**Issue by psmulovics** [finos/ambassadors#9]
On the last ambassador meeting, we discussed, that due to us being a different role than (board|leadership|etc) as we need to be 'approachable' by definition of what an ambassador is, we would get a similar voting as for the location ongoing.

**Action Needed:**
Ambassadors, please confirm if you are okay with including your linkedin by giving this issue a 👍 reaction.

**Note:**
If you have any concerns or would like to discuss further, feel free to comment below.

**Comment by eteridvalishvili** [comment]
Hi @psmulovics While reviewing the landing page recently, I noticed that the LinkedIn accounts are already included. 

They are only visible once you click on the ambassador’s name, allowing you to view their bio and LinkedIn. I can work on displaying this information more prominently, but I believe this issue is ready to be closed for now.

**Comment by psmulovics** [comment]
Ohhhh, ,that is very cool.
